version: 0.2

phases:
  install:
    runtime-versions:
      java: correto25
    commands:
      - echo "Instalando dependências do sistema"

  pre_build:
    commands:
      - echo "Iniciando validações pré-build"
      - mvn clean test-compile
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/aestheticore

  build:
    commands:
      - echo "Executando testes de integração e empacotando o .jar"
      - mvn package

  post_build:
    commands:
      - echo "Build finalizado na data `date`"
      - docker build -t REPOSITORY_URI:latest .
