spring:
  application:
    name: accesscontrol
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${COGNITO_CLIENT_ID}
            client-secret: ${COGNITO_CLIENT_SECRET}
            scope:
              - phone
              - openid
              - email
            redirect-uri: http://localhost:5173
        provider:
          cognito:
            issuerUri: ${COGNITO_ISSUER_URI}
            user-name-attribute: username