spring:
  application:
    name: accesscontrol
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: 3ea44a5qfpskvg8ogvog1l9ggv
            client-secret: <client secret>
            scope:
              - phone
              - openid
              - email
            # Spring Security by default uses a redirect-uri in the format: {baseUrl}/login/oauth2/code/{registrationId}
            # For example: http://localhost:8080/login/oauth2/code/cognito
            # See more: https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html#oauth2login-sample-redirect-uri
            redirect-uri: http://localhost:9000
        provider:
          cognito:
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_V1smI8yQw
            user-name-attribute: username